Controllers/DataController.cs
using IPM_Project.Models;
using IPM_Project.Models.Entities;
using IPM_Project.Models.Helper;
using IPM_Project.Models.SpecificViewModels;
using Microsoft.AspNetCore.Http.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IPM_Project.Controllers
{
    public class DataController : Controller
    {
        private DataManagement data;
        private LoginManagement loginManager;

        public DataController()
        {
            
            data = new DataManagement();
            this.loginManager = new LoginManagement();
            ViewBag.Login = string.Format(LoginManagement.LOGIN_MESSAGE, loginManager.GetCurrentUser().Name);
        }

        // GET: Data
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SearchDogs(FormCollection collection = null)
        {
            ViewBag.Title = "ListDogs";

            ViewBag.Message = "Form Received:\n";
            string finalMessage = string.Empty;
            foreach (string col in collection.AllKeys)
                ViewBag.Message += $"{col}: {collection[col]}\n";

            AdoptViewModel adoptViewModel = new AdoptViewModel();
            adoptViewModel.modelDog = new Dog();

            List<Dog> dogs = null;
            if (collection == null || collection.AllKeys == null || collection.AllKeys.Count() == 0)
                dogs = data.GetAllDogs();
            else
            {
                Dictionary<string, string> filters = new Dictionary<string, string>();
                foreach (string col in collection.AllKeys)
                    filters.Add(col, collection[col]);

                dogs = data.GetDogsFiltered(filters);
            }

            adoptViewModel.searchDogs = new List<Dog[]>();

            //Add the List
            if (dogs != null && dogs.Count > 0)
            {
                List<Dog> subList = new List<Dog>(AdoptViewModel.DOGS_PER_ROW);
                int i = 1;
                foreach (Dog d in dogs)
                {
                    subList.Add(d);
                    if (i == AdoptViewModel.DOGS_PER_ROW || i == dogs.Count)
                    {
                        //Add the Dog List & Clear Vars
                        i = 1;
                        adoptViewModel.searchDogs.Add(subList.ToArray());
                        subList = new List<Dog>(AdoptViewModel.DOGS_PER_ROW);
                    }
                    else
                        i++;
                }
            }

            _setViewVariables(adoptViewModel, collection);

            return View("Adopt", adoptViewModel);
        }

        private void _setViewVariables(AdoptViewModel viewModel, FormCollection collection = null)
        {
            //Define Default Options
            viewModel._categories = new List<SelectListItem>() {
                new SelectListItem{Text = "Big", Value = "BIG" },
                new SelectListItem{Text = "Medium", Value = "MEDIUM" },
                new SelectListItem{Text = "Small", Value = "SMALL" }
            };

            viewModel._gender = new List<SelectListItem>() {
                new SelectListItem{Text = "Male", Value = "MALE" },
                new SelectListItem{Text = "Female", Value = "FEMALE" },
            };

            viewModel._searchName = null;

            //Define Parameters
            if (!(
                collection == null || collection.AllKeys == null || collection.AllKeys.Count() == 0))
            {
                if (collection.AllKeys.Contains("modelDog.Category", StringComparer.InvariantCultureIgnoreCase))
                {
                    var select = viewModel._categories.
                                    Where(x => x.Value.Equals(collection["modelDog.Category"], StringComparison.InvariantCultureIgnoreCase));
                    if (select != null && select.Count() > 0)
                        select.First().Selected = true;
                }
                if (collection.AllKeys.Contains("modelDog.Gender", StringComparer.InvariantCultureIgnoreCase))
                {
                    var select = viewModel._gender.
                                  Where(x => x.Value.Equals(collection["modelDog.Gender"], StringComparison.InvariantCultureIgnoreCase));
                    if (select != null && select.Count() > 0)
                        select.First().Selected = true;
                }   
                if (collection.AllKeys.Contains("modelDog.Name", StringComparer.InvariantCultureIgnoreCase))
                    viewModel._searchName = collection["modelDog.Name"];
            }


        }

        //USEFUL LINK: https://stackoverflow.com/questions/6807256/dropdownlist-set-selected-value-in-mvc3-razor
    }
}

Controllers/FormController.cs
using IPM_Project.Models;
using IPM_Project.Models.Entities;
using IPM_Project.Models.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IPM_Project.Controllers
{
    public class FormController : Controller
    {
        private DataManagement dataManager;
        private LoginManagement loginManager;

        public FormController()
        {
            this.loginManager = new LoginManagement();
            ViewBag.Login = string.Format(LoginManagement.LOGIN_MESSAGE, loginManager.GetCurrentUser().Name);
        }

        // GET: Form
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AdoptDogForm(int dogId, string dogName)
        {
            ViewBag.Title = $"Adopt {dogName}";

            try
            {
                //Load all the Dogs
                dataManager = new DataManagement();
    

                Dog dog = dataManager.GetDogById(dogId);

                return View("AdoptDogForm", dog);
            }
            catch
            {
                return View();
            }
        }

        public ActionResult SponsorDogForm(int dogId, string dogName)
        {
            ViewBag.Title = $"Sponsor {dogName}";

            try
            {
                //Load all the Dogs
                dataManager = new DataManagement();
    

                Dog dog = dataManager.GetDogById(dogId);

                return View("SponsorDogForm", dog);
            }
            catch
            {
                return View();
            }
        }

        public ActionResult DonatingForm()
        {
            ViewBag.Title = "Make a Donation";

            return View();
        }

        public ActionResult PartnerForm()
        {
            ViewBag.Title = "Become a Partner";

            return View();
        }

        public ActionResult SurrenderDogForm()
        {
            ViewBag.Title = "Surrender a Dog";

            return View();
        }

        public ActionResult VolunteeringForm()
        {
            ViewBag.Title = "Become a Volunteer";

            return View();
        }


        public ActionResult ReceiveForm(FormCollection form, string type)
        {
            ViewBag.Title = "Initialize";

            try
            {
                this.dataManager = new DataManagement();
    

                dataManager.SubmitForm(form, type, loginManager.GetCurrentUser());

                ViewBag.Title = $"Form {type} submitted successfully";

                ViewBag.Message = $"We are now going to analize your submission and will answer to your request as soon as possible.";

                return View("ResponseForm");
            }
            catch(Exception ex)
            {
                ViewBag.Title = $"Something went wrong! Form {type} not submitted.";

                ViewBag.Message = $"Error: {ex.Message}.";

                return View("ResponseForm");
            }
        }
    }
}

Controllers/HomeController.cs
using IPM_Project.Models;
using IPM_Project.Models.Entities;
using IPM_Project.Models.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IPM_Project.Controllers
{
    /// <summary>
    /// DR
    /// Initial Pages
    /// Pages that are directly reached from the Home
    /// This pages shouldn't have much Logic. They should be the starting point for more complex and data requests
    /// </summary>
    public class HomeController : Controller
    {
        private LoginManagement loginManager;
        private FeedManagement feedManager;

        public HomeController()
        {      
            this.loginManager = new LoginManagement();
            ViewBag.Login = string.Format(LoginManagement.LOGIN_MESSAGE, loginManager.GetCurrentUser().Name);
        }

        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";

            feedManager = new FeedManagement();
            Feed mainFeed = new Feed();
            Feed feed = feedManager.GetGeneralFeed();
            Feed userFeed = feedManager.GetUserFeed(this.loginManager.GetCurrentUser());

            mainFeed.feedNews.AddRange(feed.feedNews);
            mainFeed.feedNews.AddRange(userFeed.feedNews);

            mainFeed.feedNews = mainFeed.feedNews.OrderByDescending(x => x.publishTime).ToList();

            return View("Index", mainFeed);
        }

        public ActionResult HelpUs()
        {
            ViewBag.Title = "Help Us Page.";

            return View();
        }

        public ActionResult ContactUs()
        {
            ViewBag.Title = "Contact Us Page.";

            return View();
        }
    }
}

Views/Home/ContactUs.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p class="h1">ContactUs</p>

<style>

    #m {
        height: 403px;
        width: 100%;        
    }

</style>

<p> You can contact us through:</p>
<p> &emsp; Mail: uniaozoofila@gmail.com</p>
<p> &emsp; Telephone: +351 929 038 656</p>

<p> You can also find us in:</p>
<p> &emsp; <a href="https://www.instagram.com/uniao.zoofila/">Instagram</a></p>
<p> &emsp; <a href="https://twitter.com/uniaozoofila">Twitter</a></p>
<p> &emsp; <a href="https://www.facebook.com/uniaozoofila">Facebook</a></p>

<p>
    And, of course, if you are willing to pay us a visit, our shelter is at  Rua Padre Carlos dos Santos, Alto das Furnas 1500 - 901, Lisboa.
</p>

<div id="m"></div>
<script>
    function initMap() {
        var loc = { lat: 38.741140, lng: -9.173680 };
        var m1 = new google.maps.Map(document.getElementById('m'), { zoom: 15, center: loc });
        var mar = new google.maps.Marker({ position: loc, map: m1 });
    }
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCn4y5mskINGpExWjup583ICkfDYTlZl88&callback=initMap">
</script>

Views/Home/HelpUs.cshtml
@{
    ViewBag.Title = "HelpUs";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    div {
        text-align:justify;
    }
</style>

<div class="container-fluid">
    <!-- Volunteering Form -->
    <div class="modal-body row" style="display: flex;">
        <div class="col-md-6" style="background-image: url('../images/volunteer.jpg');
                                     background-size: cover;
                                     background-repeat: no-repeat">
        </div>
        <div class="col-md-6">
            <p>
                <div class="text-center">
                    <p class="h1">Volunteering</p>
                </div>
                <br />
                Volunteering is one of the main necessities of our shelter. Cleaning our companion's
                boxes, brushing them, pamper them, organizing their rations,... These are all part
                of a volunteer's job so, be prepared!
                <br />
                <br />
                <div class="text-center">
                    <a href=@Url.Action("VolunteeringForm", "Form")
                       class="btn btn-primary btn-lg">
                        Become a Volunteer &raquo;
                    </a>
                    <br /> <br />
                    <hr />
                </div>
            </p>
        </div>
        <br />
        <hr />
    </div>

    <!-- Become a Partner Form -->
    <div class="modal-body row" style="display: flex;">
        <div class="col-md-6" style="background-image: url('../images/partner.jpg');
                                     background-size: cover;
                                     background-repeat: no-repeat">
        </div>
        <div class="col-md-6">
            <p>
                <div class="text-center">
                    <p class="h1">Become a Partner</p>
                </div>
                <br />
                Our shelter has only survived due to the help of everyone that trusts our work!
                Anyone can become a partner by paying the annual amount of 28 € after filling form.
                <br />
                <br />
                <div class="text-center">
                    <a href=@Url.Action("PartnerForm", "Form")
                       class="btn btn-primary btn-lg">
                        Become a Partner &raquo;
                    </a>
                    <br /> <br />
                    <hr />
                </div>
            </p>
        </div>
        <br />
        <hr />
    </div>

    <!-- Donating Form -->
    <div class="modal-body row" style="display: flex;">
        <div class="col-md-6" style="background-image: url('../images/donate.jpg');
                                     background-size: cover;
                                     background-repeat: no-repeat">
        </div>
        <div class="col-md-6">
            <p>
                <div class="text-center">
                    <p class="h1">Donating</p>
                </div>
                <br />
                If you also sympathize with the animal cause and want to contribute to it, but you are unable to become a partner, then a donation
                is already of great help!
                <br />
                <br />
                <div class="text-center">
                    <a href=@Url.Action("DonatingForm", "Form")
                       class="btn btn-primary btn-lg">
                        Donate &raquo;
                    </a>
                    <br /> <br />
                    <hr />
                </div>
            </p>
        </div>
        <br />
        <hr />
    </div>

    <!-- Surrender a Dog Form -->
    <div class="modal-body row" style="display: flex;">
        <div class="col-md-6" style="background-image: url('../images/surrenderDog.jpg');
                                     background-size: cover;
                                     background-repeat: no-repeat">
        </div>
        <div class="col-md-6">
            <p>
                <div class="text-center">
                    <p class="h1">Surrender a Dog</p>
                </div>
                <br />
                It is never easy to tackle a topic such as this, but if you ever feel like you cannot provide for your companion, know that we are
                here not only to take care of him/her, but also to find him/her a new home.
                <br />
                <br />
                <div class="text-center">
                    <a href=@Url.Action("SurrenderDogForm", "Form")
                       class="btn btn-primary btn-lg"
                       style="">
                        Surrender a Dog &raquo;
                    </a>
                    <br /> <br />
                    <hr />
                </div>
            </p>
        </div>
    </div>
</div>

Views/Home/Index.cshtml
@model IPM_Project.Models.Entities.Feed

<link rel="stylesheet" href="~/Style/Homepage.css">

<div class="container-fluid" id="hotLinks">
    <div class="modal-body row" style="display: flex; min-height:300px">
        <div class="col-md-6" style="background-image: url('images/Dogs_Adopt_Background.jpeg');
                                     background-size: cover;
                                     background-repeat: no-repeat;
                                     background-position: 58.33325% center;
                                     display: block;
                                     border-radius: 2%">
            
            <div id="HomePageButton" style="float: right; margin-top: 190px">
                <a href=@Url.Action("SearchDogs", "Data") role="button"
                   class="btn btn-default btn-lg">
                    Adopt Us &raquo;
                </a>
            </div>
        </div>
        <div class="col-md-6" style="background-image: url('images/People_HelpUs_Background.jpeg');
                                     background-size: cover;
                                     background-repeat: no-repeat;
                                     background-position: 58.33325% center;
                                     display: block;
                                     border-radius: 2%">
            <div id="HomePageButton" style="float: right; margin-top: 190px">
                <a href=@Url.Action("HelpUs", "Home") role="button"
                    class="btn btn-default btn-lg">
                    Help Us &raquo;
                </a>
            </div>
        </div>
    </div>
</div>

<hr />

<div class="container-fluid" id="feedNews">
    @if (Model != null && Model.feedNews.Count() > 0)
    {
        foreach (IPM_Project.Models.Entities.News row in Model.feedNews)
        {
            <div class="modal-body row" style="display: flex;">
                <div class="col-md-6" style="background-image: url('@row.figure');
                                    background-size: cover;
                                    background-repeat: no-repeat">
                    <br />
                </div>
                <div class="col-md-6">
                    <div class="text-center">
                        <p class="h1">@row.title</p>
                    </div>
                    <div class="text-left">
                        <p>@row.news</p>
                    </div>
                    <br />
                    <div class="text-right">
                        <small>@row.publishTime</small>
                    </div>
                    <br />
                    <hr />
                </div>
            </div>
        }
    }
    else
    {
        <div class="row">
            Sorry, for the moment there is no news...
        </div>
    }
</div>

<!-- TO SEE TO OPTIMIZE DISPLAY CSS
    https://stackoverflow.com/questions/43271669/how-to-add-full-width-background-in-two-column-col-md-6-on-bootstrap-3
    -->